# Generated by Django 4.1.1 on 2022-09-24 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_alter_product_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="priceAfterDiscount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="priceBeforeDiscount",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="shippingFee",
            field=models.IntegerField(default=0),
        ),
    ]
