# Generated by Django 4.1.1 on 2022-09-24 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_product_priceafterdiscount_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="product", name="price",),
    ]
