# Generated by Django 4.1.1 on 2022-09-27 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_remove_order_address_remove_order_phone_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="customer", old_name="first_name", new_name="username",
        ),
        migrations.RemoveField(model_name="customer", name="last_name",),
    ]
