# Generated by Django 4.1.1 on 2022-09-28 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_rename_first_name_customer_username_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="order", name="product",),
        migrations.AlterField(
            model_name="shippingdetail",
            name="City",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
