# Generated by Django 4.1.1 on 2022-09-29 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0008_remove_order_product_alter_shippingdetail_city"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="paymentMethod",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AlterField(
            model_name="shippingdetail",
            name="City",
            field=models.DateField(blank=True, default="", max_length=50),
        ),
    ]
