# Generated by Django 4.1.1 on 2022-09-29 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0009_order_paymentmethod_alter_shippingdetail_city"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
