# Generated by Django 4.1.1 on 2022-09-29 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_alter_order_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(blank=True, default="Pending", max_length=50),
        ),
    ]
