# Generated by Django 4.1.1 on 2022-09-29 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_rename_paymentmethod_order_paymethod"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shippingdetail",
            name="City",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
