# Generated by Django 4.1.1 on 2022-09-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_alter_shippingdetail_city"),
    ]

    operations = [
        migrations.DeleteModel(name="OrderItem",),
    ]
