# Generated by Django 4.1.1 on 2022-09-29 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0015_orderitem"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="description", new_name="company",
        ),
    ]
